<?php

namespace AppBundle\Repository;

/**
 * DayPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
