<?php

namespace AppBundle\Repository;

/**
 * DinnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinnerRepository extends \Doctrine\ORM\EntityRepository
{
}
