<?php

namespace AppBundle\Repository;

/**
 * FiltersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiltersRepository extends \Doctrine\ORM\EntityRepository
{
}
