<?php

namespace AppBundle\Repository;
use AppBundle\Controller\RawController;
/**
 * GenerateRawRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenerateRawRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('username' => RawController::class->getUser()->getId()));
    }
}
