<?php

namespace AppBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($value)
    {
        return $this->createQueryBuilder('c')
            ->andWhere('c.name like :query')
            ->setParameter('query', "%". $value ."%")
            // ->orderBy('c.id', 'ASC')
            // ->setMaxResults(10)
            ->getQuery()
            ->getResult()
            ;
    }
}
