<?php

namespace AppBundle\Repository;

/**
 * RecipeSRawRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeSRawRepository extends \Doctrine\ORM\EntityRepository
{
}
