<?php
/**
 * Created by PhpStorm.
 * User: Yonko
 * Date: 10-Jan-19
 * Time: 8:30 PM
 */

namespace AppBundle\Repository;

/**
 * SnackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnackRepository  extends \Doctrine\ORM\EntityRepository
{

}