<?php

namespace AppBundle\Repository;

/**
 * WeekPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeekPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
